package com.cedge.poweredge.dto;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;


/**
 * Cesys004 generated by hbm2java
 */
@Entity
@Table(name = "cesys004")
@Data
public class Bank implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@Column(name = "bank_name", length = 200)
	private String bankName;
	@Column(name = "bank_code", length = 100)
	private String bankCode;
	@Column(name = "driver_class", length = 100)
	private String driverClass;
	@Column(name = "database_url", length = 100)
	private String databaseUrl;
	@Column(name = "username", length = 100)
	private String username;
	@Column(name = "password", length = 100)
	private String password;
	@Column(name = "bank_type", length = 200)
	private String banktype;

	
}