package com.cedge.poweredge.dto;

import javax.persistence.*;

import lombok.Data;

/**
 * TellerMaster generated by hbm2java
 */
@Entity
@Table(name = "teller_master")
@Data
public class TellerMaster implements java.io.Serializable {
	
	private static final long serialVersionUID = -7576808287358423189L;

	@Id
	@Column(name = "TELLERID")
	private String tellerid;
	@Column(name = "PWD")
	private String pwd;
	@Column(name = "CAPABILITY")
	private Long capability;
	@Column(name = "ENABLED")
	private long enabled;
	@Column(name = "TELLERTYPE")
	private Long tellertype;
	@Column(name = "IP")
	private String ip;
	@Column(name = "SIGNONCOUNT")
	private Short signoncount;
	@Column(name = "TELLER_NM")
	private String tellerNm;
	@Column(name = "BRANCHID")
	private Integer branchid;
	@Column(name = "BANK_CODE")
	private String bankCode;
	@Column(name = "ccdp",nullable=true)
	private boolean ccdp;
	@Transient
	private String bankName;

}
